[forest]
trees = ["trees", "macros", "blog"] # The directories in which your trees are stored
assets = ["assets"]                  # The directories in which your assets are stored
theme = "theme"                      # The directory in which your theme is stored


[forest]
assets = ["assets"]
theme = "theme"
home = "home"
host = "https://www.krisb.org/forest"