name: Build and Deploy Forester Site to /files

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    container:
      # Use an official OCaml/OPAM Docker image with OCaml 5.1 (a common recent version)
      image: ocaml/opam:ubuntu-ocaml-5.1
      options: --user root

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Initialize OPAM, Create OCaml 5.1 Switch, Update, and Install Forester
        run: |
          # Ensure opam init runs non-interactively regarding shell modifications
          echo -e 'n\nN' | opam init --disable-sandboxing --reinit --bare -y
          
          # Explicitly create a switch named 'default' using OCaml 5.1.1 (adjust patch if needed)
          # This should align with Forester's requirements.
          # This step will likely take time as it compiles OCaml 5.1.1 if not perfectly cached.
          opam switch create default ocaml-base-compiler.5.1.1 -y
          
          eval $(opam env)
          opam update
          
          # Install Forester
          # With OCaml 5.1.1, Forester's dependencies should resolve.
          opam install forester -y
          
          forester --version

      - name: Build Site with Forester
        run: |
          eval $(opam env)
          forester build forest.toml

      - name: Deploy to gwesley96.github.io/files
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.GH_PAGES_PAT }}
          external_repository: gwesley96/gwesley96.github.io
          publish_branch: main
          publish_dir: ./output
          target_dir: files
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: Deploy to /files (automated build from source repo)