name: Build and Deploy Forester Output

on:
  push:
    branches:
      - main # In your Forester project repository

jobs:
  build-and-deploy-forester:
    runs-on: ubuntu-latest

    container:
      image: ocaml/opam:ubuntu-ocaml-5.1
      options: --user root # Continue running as root

    steps:
      - name: Checkout Forester source code
        uses: actions/checkout@v4
        # If your Forester project uses Git submodules (e.g., for its theme):
        # with:
        #   submodules: 'recursive'

      - name: Cache OPAM packages for root user
        id: cache-opam
        uses: actions/cache@v4
        with:
          path: /root/.opam # OPAM root for the root user
          key: ${{ runner.os }}-ocaml5.1-opam-root-${{ hashFiles('**/forest.toml\n**/*.opam\n**/opam.lock') }}
          restore-keys: |
            ${{ runner.os }}-ocaml5.1-opam-root-

      - name: Set up OPAM, Install/Update Forester
        shell: bash
        run: |
          set -e # Exit immediately if a command exits with a non-zero status

          # Explicitly define OPAMROOT for this script and for GITHUB_ENV
          # This variable name OPAM_ROOT_DIR is what subsequent steps will use from GITHUB_ENV
          export LOCAL_OPAM_ROOT_DIR="/root/.opam"
          echo "OPAM_ROOT_DIR=${LOCAL_OPAM_ROOT_DIR}" >> $GITHUB_ENV

          echo "Initializing OPAM for root at ${LOCAL_OPAM_ROOT_DIR} (using --auto-setup)..."
          # --auto-setup is designed for non-interactive use and should handle shell config quietly.
          opam init --root="${LOCAL_OPAM_ROOT_DIR}" --reinit --disable-sandboxing --auto-setup
          
          echo "Setting up OCaml switch 'default' (OCaml 5.1.1) at ${LOCAL_OPAM_ROOT_DIR}..."
          # Source env after init to make current OPAMROOT active for switch commands for this step
          eval $(opam env --root="${LOCAL_OPAM_ROOT_DIR}" --set-root) 

          # Create 'default' switch if it doesn't exist, then ensure it's set.
          if ! opam switch list | grep -q "^default "; then
            opam switch create default ocaml-base-compiler.5.1.1 --yes
          fi
          opam switch set default
          # For subsequent steps, record the switch name
          echo "OPAM_SWITCH_NAME=default" >> $GITHUB_ENV

          echo "Setting OPAM environment variables (including switch) for this current step..."
          # This final eval sets up PATH etc. for the current switch for THIS script block.
          eval $(opam env --root="${LOCAL_OPAM_ROOT_DIR}" --switch=default --set-switch)

          echo "Verifying OCaml/OPAM versions (after full env setup for this step)..."
          opam --version
          ocaml --version
          echo "OPAM Root Directory from 'opam var root' is: $(opam var root)" # Should now work
          
          echo "Updating OPAM repositories..."
          opam update -u --yes
          
          echo "Installing Forester and its dependencies (using cache if available)..."
          opam install forester --yes --show-actions

      - name: Verify Forester Installation
        shell: bash 
        run: |
          echo "Sourcing OPAM environment for verification..."
          # Use OPAM_ROOT_DIR and OPAM_SWITCH_NAME from GITHUB_ENV (set in the previous step)
          eval $(opam env --root="${OPAM_ROOT_DIR}" --switch="${OPAM_SWITCH_NAME}" --set-switch)
          echo "Updated PATH is: $PATH"
          which forester
          forester --version

      - name: Build Forester Site
        shell: bash 
        run: |
          echo "Sourcing OPAM environment for build..."
          # Use OPAM_ROOT_DIR and OPAM_SWITCH_NAME from GITHUB_ENV
          eval $(opam env --root="${OPAM_ROOT_DIR}" --switch="${OPAM_SWITCH_NAME}" --set-switch)
          echo "Updated PATH is: $PATH"
          # Ensure forest.toml is at the root of your project, or adjust path if needed.
          forester build forest.toml 
          echo "Forester build complete. Output should be in ./output/"
          echo "Contents of ./output directory:"
          ls -la ./output

      - name: Deploy 'output' directory to gwesley96.github.io/tytytyty
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.GH_PAGES_PAT }} 
          external_repository: gwesley96/gwesley96.github.io
          # IMPORTANT: Set publish_branch to your gwesley96.github.io GitHub Pages branch (e.g., main, master, gh-pages)
          publish_branch: master 
          publish_dir: ./output    # Directory created by 'forester build'
          destination_dir: tytytyty  # Corrected parameter name
          keep_files: true         # Keeps other files in gwesley96.github.io untouched
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: 'Deploy Forester output to /tytytyty [CI]'
