      - name: Set up OPAM, Install/Update Forester
        shell: bash
        env:
          # Define OPAM_ROOT_DIR for this step's script block
          OPAM_ROOT_DIR_FOR_SETUP: /root/.opam
        run: |
          set -e # Exit immediately if a command exits with a non-zero status

          # Use the step-level env var for OPAMROOT within this script
          export OPAMROOT="${OPAM_ROOT_DIR_FOR_SETUP}"
          # For subsequent steps, write this to GITHUB_ENV
          echo "OPAM_ROOT_DIR=${OPAMROOT}" >> $GITHUB_ENV

          DESIRED_OCAML_COMPILER="ocaml-base-compiler.5.1.1"
          # This will be the name of the switch we intend to use.
          # `opam init <compiler> --auto-setup` typically creates a switch named 'default'.
          TARGET_SWITCH_NAME="default"

          echo "Initializing OPAM for root at ${OPAMROOT} with ${DESIRED_OCAML_COMPILER} (using --auto-setup)..."
          # Tell opam init to use the desired OCaml version for the switch it creates/configures.
          # --reinit ensures it works even if an OPAMROOT exists (e.g. from cache).
          # --auto-setup should handle non-interactive setup, including creating a switch
          # (typically 'default') with the specified compiler.
          opam init "${DESIRED_OCAML_COMPILER}" --reinit --disable-sandboxing --auto-setup --yes

          echo "Setting up OCaml switch '${TARGET_SWITCH_NAME}' (using ${DESIRED_OCAML_COMPILER}) at ${OPAMROOT}..."
          # Source env after init to make current OPAMROOT active for switch commands for this step
          eval $(opam env --set-root) # Uses OPAMROOT from current env

          # `opam init` with a compiler and --auto-setup should have created and set up
          # a switch (usually 'default') with that compiler. We just ensure it's selected.
          # If `opam init` named the switch something else (e.g., "5.1.1" instead of "default"),
          # this would need adjustment, but 'default' is the most common behavior.
          opam switch set "${TARGET_SWITCH_NAME}" # Ensure this switch is the current one.

          # For subsequent steps, record the switch name
          echo "OPAM_SWITCH_NAME=${TARGET_SWITCH_NAME}" >> $GITHUB_ENV

          echo "Setting full OPAM environment variables (including switch) for this current step..."
          # This final eval sets up PATH etc. for the TARGET_SWITCH_NAME for THIS script block.
          eval $(opam env --switch="${TARGET_SWITCH_NAME}" --set-switch) # Uses OPAMROOT from current env

          echo "Verifying OCaml/OPAM versions (after full env setup for this step)..."
          opam --version
          ocaml --version
          echo "OPAM Root Directory from 'opam var root' is: $(opam var root)"
          echo "Current OPAM switch from 'opam var switch' is: $(opam var switch)"
          # Verify that the active switch is indeed using the desired OCaml compiler
          if ! opam switch show "${TARGET_SWITCH_NAME}" | grep -q "${DESIRED_OCAML_COMPILER}"; then
            echo "Error: Switch '${TARGET_SWITCH_NAME}' is not using ${DESIRED_OCAML_COMPILER}!"
            echo "Switch details:"
            opam switch show "${TARGET_SWITCH_NAME}"
            exit 1
          fi

          echo "Updating OPAM repositories..."
          opam update -u --yes

          echo "Installing Forester and its dependencies (using cache if available)..."
          opam install forester --yes --show-actions
