name: Build and Deploy Forester Site to /files

on:
  push:
    branches:
      - main # 1. IMPORTANT: Change 'main' if your source repo's default branch is different

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    container:
      image: ocaml/opam:ubuntu-ocaml-4.14
      # Add this option to run the container as the root user
      options: --user root

    steps:
      # No explicit chmod step needed here anymore if running as root,
      # as root will have permissions.

      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Update OPAM and Install Forester
        run: |
          # Running as root, opam commands should work fine.
          # Some opam setups might complain about running as root, but usually it's for safety
          # in interactive use, less so in CI where the container is ephemeral.
          opam update
          opam install forester -y --no-depexts
          forester --version

      - name: Build Site with Forester
        run: forester build forest.toml

      - name: Deploy to gwesley96.github.io/files
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.GH_PAGES_PAT }}
          external_repository: gwesley96/gwesley96.github.io
          publish_branch: main
          publish_dir: ./output
          target_dir: files
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: Deploy to /files (automated build from source repo)