name: Build and Deploy Forester Output

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy-forester:
    runs-on: ubuntu-latest
    container:
      image: ocaml/opam:ubuntu-ocaml-5.1
      options: --user root

    steps:
      - name: Checkout Forester source code
        uses: actions/checkout@v4

      - name: Cache OPAM packages for root user
        id: cache-opam
        uses: actions/cache@v4
        with:
          path: /root/.opam
          key: ${{ runner.os }}-ocaml5.1-opam-root-${{ hashFiles('**/forest.toml', '**/*.opam', '**/opam.lock') }}
          restore-keys: |
            ${{ runner.os }}-ocaml5.1-opam-root-

      - name: Set up OPAM, Install/Update Forester
        shell: bash
        env:
          OPAM_ROOT_DIR_FOR_SETUP: /root/.opam
        run: |
          set -e
          export OPAMROOT="$OPAM_ROOT_DIR_FOR_SETUP"
          echo "OPAM_ROOT_DIR=${OPAMROOT}" >> $GITHUB_ENV

          DESIRED_OCAML_COMPILER="ocaml-base-compiler.5.1.1"
          TARGET_SWITCH_NAME="default"

          opam init --reinit --disable-sandboxing --bare --yes
          eval $(opam env --set-root)

          if opam switch list --short | grep -q -E "^${TARGET_SWITCH_NAME}\s*$"; then
            opam switch set "${TARGET_SWITCH_NAME}"
            eval $(opam env --switch="${TARGET_SWITCH_NAME}" --set-switch)
            EXISTING_COMPILER=$(opam list --installed | grep -E "^ocaml-base-compiler" | awk '{print $1"."$2}' || echo "")
            if [ "$EXISTING_COMPILER" != "$DESIRED_OCAML_COMPILER" ]; then
              opam switch remove "${TARGET_SWITCH_NAME}" --yes
              opam switch create "${TARGET_SWITCH_NAME}" "${DESIRED_OCAML_COMPILER}" --yes
            fi
          else
            opam switch create "${TARGET_SWITCH_NAME}" "${DESIRED_OCAML_COMPILER}" --yes
          fi

          opam switch set "${TARGET_SWITCH_NAME}"
          echo "OPAM_SWITCH_NAME=${TARGET_SWITCH_NAME}" >> $GITHUB_ENV
          eval $(opam env --switch="${TARGET_SWITCH_NAME}" --set-switch)

          opam update -u --yes

          echo "Installing Forester and its dependencies..."
          opam install forester --yes

          echo "Reloading OPAM env to include Forester"
          eval $(opam env --root="$OPAMROOT" --switch="${TARGET_SWITCH_NAME}" --set-switch)

      - name: Verify Forester Installation
        shell: bash
        run: |
          export OPAMROOT="${OPAM_ROOT_DIR}"
          export OPAMSWITCH="${OPAM_SWITCH_NAME}"
          eval $(opam env --set-switch)
          echo "PATH: $PATH"
          which forester
          forester --version

      - name: Build Forester Site
        shell: bash
        run: |
          export OPAMROOT="${OPAM_ROOT_DIR}"
          export OPAMSWITCH="${OPAM_SWITCH_NAME}"
          eval $(opam env --set-switch)
          forester build forest.toml

      - name: Deploy 'output' directory to gwesley96.github.io/wiki
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.GH_PAGES_PAT }}
          external_repository: gwesley96/gwesley96.github.io
          publish_branch: master
          publish_dir: ./output
          destination_dir: wiki
          keep_files: true
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: 'Deploy Forester output to /wiki [CI]'
          enable_jekyll: true
