name: Build and Deploy Forester Output

on:
  push:
    branches:
      - main # In your Forester project repository

jobs:
  build-and-deploy-forester:
    runs-on: ubuntu-latest

    container:
      image: ocaml/opam:ubuntu-ocaml-5.1
      options: --user root # Continue running as root

    steps:
      - name: Checkout Forester source code
        uses: actions/checkout@v4
        # If your Forester project uses Git submodules (e.g., for its theme):
        # with:
        #   submodules: 'recursive'

      - name: Cache OPAM packages for root user
        id: cache-opam
        uses: actions/cache@v4
        with:
          path: /root/.opam # OPAM root for the root user
          key: ${{ runner.os }}-ocaml5.1-opam-root-${{ hashFiles('**/forest.toml\n**/*.opam\n**/opam.lock') }}
          restore-keys: |
            ${{ runner.os }}-ocaml5.1-opam-root-

      - name: Set up OPAM, Install/Update Forester
        shell: bash
        run: |
          set -e 
          export OPAMROOT="/root/.opam" # Define OPAMROOT for this script session

          echo "Initializing OPAM for root (non-interactively)..."
          echo -e "n\nn" | opam init --reinit --bare --disable-sandboxing --yes
          
          echo "Setting up OCaml switch for root..."
          if ! opam switch list | grep -q "^default "; then
            opam switch create default ocaml-base-compiler.5.1.1 --yes
          fi
          opam switch set default

          echo "Setting OPAM environment variables for subsequent steps..."
          opam env --set-root --set-switch >> $GITHUB_ENV # Make env vars available to later steps
          
          # Also eval for the current step to use it immediately
          eval $(opam env --set-root --set-switch)

          echo "Verifying OCaml/OPAM versions (after env setup)..."
          opam --version
          ocaml --version
          echo "OPAM Root Directory from 'opam var root' is: $(opam var root)"
          
          echo "Updating OPAM repositories..."
          opam update -u --yes
          
          echo "Installing Forester and its dependencies (using cache if available)..."
          opam install forester --yes --show-actions

      - name: Verify Forester Installation
        shell: bash 
        run: |
          echo "Sourcing OPAM environment for verification..."
          eval $(opam env --root=/root/.opam --set-switch) # Explicitly source env
          echo "Updated PATH is: $PATH"
          which forester  # This will show if/where 'forester' is found
          forester --version

      - name: Build Forester Site
        shell: bash 
        run: |
          echo "Sourcing OPAM environment for build..."
          eval $(opam env --root=/root/.opam --set-switch) # Explicitly source env
          echo "Updated PATH is: $PATH"
          # Ensure forest.toml is at the root of your project, or adjust path if needed.
          forester build forest.toml 
          echo "Forester build complete. Output should be in ./output/"
          echo "Contents of ./output directory:"
          ls -la ./output

      - name: Deploy 'output' directory to gwesley96.github.io/tytytyty
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.GH_PAGES_PAT }} 
          external_repository: gwesley96/gwesley96.github.io
          publish_branch: master 
          publish_dir: ./output
          destination_dir: tytytyty 
          keep_files: true
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: 'Deploy Forester output to /tytytyty [CI]'
