name: Build and Deploy Forester Site to /files

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    container:
      image: ocaml/opam:ubuntu-ocaml-5.1
      options: --user root # Note: Running as root has security implications. Consider if necessary.

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Initialize OPAM, Create OCaml 5.1 Switch, Update, and Install Forester
        run: |
          echo -e 'n\nN' | opam init --disable-sandboxing --reinit --bare -y
          opam switch create default ocaml-base-compiler.5.1.1 -y
          eval $(opam env)
          opam update
          opam install forester -y
          forester --version

      - name: DEBUG - List files BEFORE build
        run: |
          echo "Listing files BEFORE Forester build in $(pwd):"
          ls -laR
          echo "--- End of pre-build file listing ---"

      - name: Build Site with Forester
        run: |
          eval $(opam env)
          echo "Running: forester build forest.toml"
          forester build forest.toml
          echo "Forester build command finished."

      - name: DEBUG - List files AFTER build (especially output dir)
        run: |
          echo "Listing files AFTER Forester build in $(pwd):"
          ls -laR
          echo "--- Looking specifically inside ./output (if it exists) ---"
          if [ -d "./output" ]; then
            echo "Contents of ./output:"
            ls -laR ./output
          else
            echo "./output directory NOT FOUND!"
          fi
          echo "--- End of post-build file listing ---"

      - name: Deploy to gwesley96.github.io/files
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.GH_PAGES_PAT }}
          external_repository: gwesley96/gwesley96.github.io
          publish_branch: master # Or main, depending on your GitHub Pages source branch for gwesley96.github.io
          publish_dir: ./output
          target_dir: files
          keep_files: true # <--- THIS IS THE CRUCIAL ADDITION
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: Deploy to /files (automated build from source repo)
          # force_orphan: false # Default is false, but explicitly setting it can sometimes help if keep_files isn't enough
          # allow_empty_commit: false # Default, usually fine