name: Build and Deploy Forester Output

on:
  push:
    branches:
      - main # In your Forester project repository

jobs:
  build-and-deploy-forester:
    runs-on: ubuntu-latest

    container:
      image: ocaml/opam:ubuntu-ocaml-5.1
      options: --user root # Continue running as root

    steps:
      - name: Checkout Forester source code
        uses: actions/checkout@v4

      - name: Cache OPAM packages for root user
        id: cache-opam
        uses: actions/cache@v4
        with:
          path: /root/.opam # OPAM root for the root user
          key: ${{ runner.os }}-ocaml5.1-opam-root-${{ hashFiles('**/forest.toml\n**/*.opam\n**/opam.lock') }}
          restore-keys: |
            ${{ runner.os }}-ocaml5.1-opam-root-

      - name: Set up OPAM, Install/Update Forester
        shell: bash
        run: |
          set -e 
          # Explicitly define OPAMROOT for this script and for GITHUB_ENV
          export OPAM_ROOT_DIR="/root/.opam"
          echo "OPAM_ROOT_DIR=${OPAM_ROOT_DIR}" >> $GITHUB_ENV # For subsequent steps

          echo "Initializing OPAM for root (non-interactively) at ${OPAM_ROOT_DIR}..."
          echo -e "n\nn" | opam init --root="${OPAM_ROOT_DIR}" --reinit --bare --disable-sandboxing --yes
          
          echo "Setting up OCaml switch 'default' (OCaml 5.1.1) for root at ${OPAM_ROOT_DIR}..."
          # Create 'default' switch if it doesn't exist, then ensure it's set.
          if ! opam switch list --root="${OPAM_ROOT_DIR}" | grep -q "^default "; then
            opam switch create default ocaml-base-compiler.5.1.1 --root="${OPAM_ROOT_DIR}" --yes
          fi
          opam switch set default --root="${OPAM_ROOT_DIR}"
          echo "OPAM_SWITCH_NAME=default" >> $GITHUB_ENV # For subsequent steps

          # Set up the environment for the CURRENT step using the explicit root and switch
          eval $(opam env --root="${OPAM_ROOT_DIR}" --switch=default --set-switch)

          echo "Verifying OCaml/OPAM versions (after env setup)..."
          opam --version
          ocaml --version
          echo "OPAM Root Directory from 'opam var root' is: $(opam var root)"
          
          echo "Updating OPAM repositories..."
          opam update -u --yes
          
          echo "Installing Forester and its dependencies (using cache if available)..."
          opam install forester --yes --show-actions

      - name: Verify Forester Installation
        shell: bash 
        run: |
          echo "Sourcing OPAM environment for verification..."
          # Use OPAM_ROOT_DIR and OPAM_SWITCH_NAME from GITHUB_ENV
          eval $(opam env --root="${OPAM_ROOT_DIR}" --switch="${OPAM_SWITCH_NAME}" --set-switch)
          echo "Updated PATH is: $PATH"
          which forester
          forester --version

      - name: Build Forester Site
        shell: bash 
        run: |
          echo "Sourcing OPAM environment for build..."
          # Use OPAM_ROOT_DIR and OPAM_SWITCH_NAME from GITHUB_ENV
          eval $(opam env --root="${OPAM_ROOT_DIR}" --switch="${OPAM_SWITCH_NAME}" --set-switch)
          echo "Updated PATH is: $PATH"
          forester build forest.toml 
          echo "Forester build complete. Output should be in ./output/"
          echo "Contents of ./output directory:"
          ls -la ./output

      - name: Deploy 'output' directory to gwesley96.github.io/tytytyty
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.GH_PAGES_PAT }} 
          external_repository: gwesley96/gwesley96.github.io
          publish_branch: master 
          publish_dir: ./output
          destination_dir: tytytyty 
          keep_files: true
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: 'Deploy Forester output to /tytytyty [CI]'
