name: Build and Deploy Forester Site to /files

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Set up OCaml (manual opam init)
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: '4.14.0' # Pinning to a specific common version

      - name: Initialize OPAM and Install Forester
        run: |
          # opam init can sometimes ask for confirmation, --disable-sandboxing is often needed in CI
          # The 'eval $(opam env)' configures the shell environment.
          opam init --disable-sandboxing --reinit -y
          eval $(opam env)
          opam update
          # Now install Forester, explicitly saying no to depext for this package installation
          opam install forester --no-depexts -y
          forester --version

      - name: Build Site with Forester
        run: |
          eval $(opam env) # Ensure OCaml/Forester environment is active
          forester build forest.toml

      - name: Deploy to gwesley96.github.io/files
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.GH_PAGES_PAT }}
          external_repository: gwesley96/gwesley96.github.io
          publish_branch: main
          publish_dir: ./output
          target_dir: files
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: Deploy to /files (automated build from source repo)