name: Build and Deploy Forester Output

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy-forester:
    runs-on: ubuntu-latest
    container:
      image: ocaml/opam:ubuntu-ocaml-5.1
      options: --user root

    steps:
      - name: Checkout Forester source code
        uses: actions/checkout@v4

      - name: Cache OPAM packages
        id: cache-opam
        uses: actions/cache@v4
        with:
          path: /root/.opam 
          key: <span class="math-inline">\{\{ runner\.os \}\}\-ocaml5\.1\-opam\-root\-</span>{{ hashFiles('**/forest.toml', '**/*.opam', '**/opam.lock') }}
          restore-keys: |
            ${{ runner.os }}-ocaml5.1-opam-root-

      - name: Set up OPAM, Install/Update Forester & Dependencies
        shell: bash # Ensures subcommands run in the same shell context for `eval`
        run: |
          set -e # Exit immediately if a command exits with a non-zero status.

          echo "Initializing OPAM and OCaml Switch..."
          # Initialize OPAM for the root user if it hasn't been done from a cache restore.
          # Use --bare if ~/.opam exists but is just a placeholder from cache.
          # Use --reinit to ensure it's usable.
          opam init --root=/root/.opam --reinit --bare --disable-sandboxing --yes
          
          # Create or ensure the OCaml 5.1.1 switch exists.
          opam switch list --root=/root/.opam | grep -q "default" || opam switch create default ocaml-base-compiler.5.1.1 --root=/root/.opam --yes
          opam switch set default --root=/root/.opam

          # Set up the environment for OPAM for subsequent commands in this step
          eval $(opam env --root=/root/.opam --set-switch)
          
          echo "Verifying OCaml/OPAM versions..."
          opam --version
          ocaml --version
          echo "OPAM Root Directory is: $(opam var root)"
          
          echo "Updating OPAM repositories..."
          opam update -u --yes
          
          echo "Installing Forester and its dependencies (will use cache if possible)..."
          opam install forester --yes --depexts --show-actions

      - name: Verify Forester Installation
        shell: bash # Use bash and eval here too
        run: |
          eval $(opam env --root=/root/.opam --set-switch)
          forester --version

      - name: Build Forester Site
        shell: bash # Use bash and eval here too
        run: |
          eval $(opam env --root=/root/.opam --set-switch)
          forester build forest.toml 
          echo "Forester build complete. Output should be in ./output/"
          echo "Contents of ./output directory:"
          ls -la ./output

      - name: Deploy 'output' directory to gwesley96.github.io/tytytyty
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.GH_PAGES_PAT }}
          external_repository: gwesley96/gwesley96.github.io
          publish_branch: master 
          publish_dir: ./output
          destination_dir: tytytyty
          keep_files: true
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: 'Deploy Forester output to /tytytyty [CI]'