name: Build and Deploy Forester Site to /files

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    container:
      image: ocaml/opam:ubuntu-ocaml-4.14
      options: --user root # Run the container as the root user

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Initialize OPAM, Update, and Install Forester
        run: |
          # Initialize OPAM for the root user since we are running as root.
          # --disable-sandboxing is often needed in CI environments.
          # -a automatically selects the default OCaml compiler.
          # -y automatically confirms prompts.
          opam init --disable-sandboxing -a -y

          # The 'opam init' command should have updated the environment,
          # but 'eval $(opam env)' ensures it's correctly sourced for this shell session.
          eval $(opam env)

          opam update
          opam install forester -y --no-depexts # --no-depexts is a precaution
          forester --version

      - name: Build Site with Forester
        run: |
          # Ensure the OPAM environment is sourced for this step too
          eval $(opam env)
          forester build forest.toml

      - name: Deploy to gwesley96.github.io/files
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.GH_PAGES_PAT }}
          external_repository: gwesley96/gwesley96.github.io
          publish_branch: main
          publish_dir: ./output
          target_dir: files
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: Deploy to /files (automated build from source repo)