name: Build and Deploy Forester Site to /files

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    container:
      image: ocaml/opam:ubuntu-ocaml-4.14
      options: --user root

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Initialize OPAM, Create Switch, Update, and Install Forester
        run: |
          # Ensure opam init runs non-interactively regarding shell modifications
          # Pipe 'n' and then 'N' to the prompts for modifying .profile and setting up hooks
          # --disable-sandboxing for CI, --reinit for robustness
          echo -e 'n\nN' | opam init --disable-sandboxing --reinit --bare -y
          
          # Explicitly create a switch named 'default' using OCaml 4.14.2 (adjust patch if needed)
          # This refers to the compiler package itself.
          opam switch create default ocaml-base-compiler.4.14.2 -y
          
          eval $(opam env)
          opam update
          
          # Install Forester
          opam install forester -y
          
          forester --version

      - name: Build Site with Forester
        run: |
          eval $(opam env)
          forester build forest.toml

      - name: Deploy to gwesley96.github.io/files
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.GH_PAGES_PAT }}
          external_repository: gwesley96/gwesley96.github.io
          publish_branch: main
          publish_dir: ./output
          target_dir: files
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: Deploy to /files (automated build from source repo)