name: Build and Deploy Forester Output

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy-forester:
    runs-on: ubuntu-latest

    container:
      image: ocaml/opam:ubuntu-ocaml-5.1
      options: --user root

    steps:
      - name: Checkout Forester source code
        uses: actions/checkout@v4

      - name: Cache OPAM packages for root user
        id: cache-opam
        uses: actions/cache@v4
        with:
          path: /root/.opam
          key: ${{ runner.os }}-ocaml5.1-opam-root-${{ hashFiles('**/forest.toml', '**/*.opam', '**/opam.lock') }}
          restore-keys: |
            ${{ runner.os }}-ocaml5.1-opam-root-

      - name: Set up OPAM, Install/Update Forester
        shell: bash
        env:
          OPAM_ROOT_DIR_FOR_SETUP: /root/.opam
        run: |
          set -e
          export OPAMROOT="${OPAM_ROOT_DIR_FOR_SETUP}"
          echo "OPAM_ROOT_DIR=${OPAMROOT}" >> $GITHUB_ENV

          echo "Initializing OPAM for root at ${OPAMROOT}..."
          opam init --reinit --disable-sandboxing --auto-setup --yes

          echo "Setting up OCaml switch 'default' (OCaml 5.1.1)..."
          eval $(opam env)

          if ! opam switch list | grep -q "^default "; then
            opam switch create default ocaml-base-compiler.5.1.1 --yes
          fi
          opam switch set default
          echo "OPAM_SWITCH_NAME=default" >> $GITHUB_ENV

          echo "Setting full OPAM environment variables for this current step..."
          eval $(opam env --switch=default --set-switch)

          echo "Verifying OCaml/OPAM versions..."
          opam --version
          ocaml --version
          echo "OPAM Root Directory: $(opam var root)"
          echo "Current OPAM switch: $(opam var switch)"

          echo "Updating OPAM repositories..."
          opam update -u --yes

          echo "Installing Forester and its dependencies..."
          opam install forester --yes --show-actions

      - name: Verify Forester Installation
        shell: bash
        run: |
          export OPAMROOT="${OPAM_ROOT_DIR}"
          export OPAMSWITCH="${OPAM_SWITCH_NAME}"
          eval $(opam env --set-switch)

          echo "Updated PATH: $PATH"
          echo "Found Forester at: $(which forester || echo 'Forester not found in PATH')"
          forester --version

      - name: Build Forester Site
        shell: bash
        run: |
          echo "Sourcing OPAM environment for build..."
          export OPAMROOT="${OPAM_ROOT_DIR}"
          export OPAMSWITCH="${OPAM_SWITCH_NAME}"
          eval $(opam env --set-switch)

          echo "Updated PATH: $PATH"
          forester build forest.toml
          echo "Forester build complete. Output should be in ./output/"
          echo "Contents of ./output directory:"
          ls -la ./output

      - name: Deploy 'output' directory to gwesley96.github.io/tytytyty
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.GH_PAGES_PAT }}
          external_repository: gwesley96/gwesley96.github.io
          publish_branch: master
          publish_dir: ./output
          destination_dir: tytytyty
          keep_files: true
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: 'Deploy Forester output to /tytytyty [CI]'
